### ISSUE TITLE
USER STORY: Add Courses

### ISSUE THREAD

**Issue by SreeshmaTharammal** [SreeshmaTharammal/PP4-CollegeConnect#7]
As an **admin**, I can **add courses**, so that I can **mange the courses available**.

### Acceptance Criteria

- **Given** that I am logged into my user account as an admin
**When** I click on option to add course 
**Then** I can specify the name and year for the course and should be able to save

### Tasks

- [ ] Task 1 - Develop a button to add course
- [ ] Task 2 - Develop an input field to input the course name 
- [ ] Task 3 - Develop an input field to input the course year
- [ ] Task 4 - Develop a button to save the course 
- [ ] Task 5 - Develop API to save course details
- [ ] Task 6 - Develop back end functionality to save the course details to database
